name: Docker Build and Push (Dynamic Tagging)

on:
  push:
    branches:
      - main
    paths:
      - '.wp-build/**'

permissions:
  packages: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to check commit messages

      - name: Determine version bump from commit message
        id: get_version_bump
        run: |
          if git log -1 --pretty=%B | grep -q "\\[M\\]"; then
            echo "bump=M" >> $GITHUB_OUTPUT
          elif git log -1 --pretty=%B | grep -q "\\[m\\]"; then
            echo "bump=m" >> $GITHUB_OUTPUT
          elif git log -1 --pretty=%B | grep -q "\\[p\\]"; then
            echo "bump=p" >> $GITHUB_OUTPUT
          else
            echo "No version bump tag ([M], [m], [p]) found in commit message."
            exit 1
          fi

      - name: Bump version
        id: bump_version
        run: |
          chmod +x ./bump-version.sh
          ./bump-version.sh ${{ steps.get_version_bump.outputs.bump }}
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .wp-build/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.bump_version.outputs.version }}
            ghcr.io/${{ github.repository }}:latest

      - name: Commit updated version and tag
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add VERSION
          git commit -m "Bump version to ${{ steps.bump_version.outputs.version }}"
          git tag ${{ steps.bump_version.outputs.version }}
          git push origin main --tags
